/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tw.edu.npu.mis;
import java.util.Observable;


/**
 *
 * @author Even
 */
public class View extends javax.swing.JFrame implements java.util.Observer{
    //宣告mCon
    Controller mCon;
  
      
    /**
     * 
     * @param mcontroller  :Controller 的Method and Attribute.
     */
      public View( Controller mcontroller) {
        mCon = mcontroller;
        initComponents();
    }

      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        display = new javax.swing.JTextField();
        bt_backspece = new javax.swing.JButton();
        bt_ce = new javax.swing.JButton();
        bt_clear = new javax.swing.JButton();
        bt_plus = new javax.swing.JButton();
        bt_over = new javax.swing.JButton();
        bt_times = new javax.swing.JButton();
        bt_equal = new javax.swing.JButton();
        bt_minus = new javax.swing.JButton();
        bt_seven = new javax.swing.JButton();
        bt_four = new javax.swing.JButton();
        bt_one = new javax.swing.JButton();
        bt_plus_minus = new javax.swing.JButton();
        bt_eight = new javax.swing.JButton();
        bt_five = new javax.swing.JButton();
        bt_two = new javax.swing.JButton();
        bt_zero = new javax.swing.JButton();
        bt_nine = new javax.swing.JButton();
        bt_three = new javax.swing.JButton();
        bt_six = new javax.swing.JButton();
        decimal = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_backspece.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_backspece.setText("←");
        bt_backspece.setMaximumSize(new java.awt.Dimension(40, 40));
        bt_backspece.setMinimumSize(new java.awt.Dimension(40, 40));
        bt_backspece.setPreferredSize(new java.awt.Dimension(44, 44));
        bt_backspece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backspeceActionPerformed(evt);
            }
        });

        bt_ce.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_ce.setText("CE");
        bt_ce.setMaximumSize(new java.awt.Dimension(40, 40));
        bt_ce.setMinimumSize(new java.awt.Dimension(40, 40));
        bt_ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ceActionPerformed(evt);
            }
        });

        bt_clear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_clear.setText("C");
        bt_clear.setMaximumSize(new java.awt.Dimension(40, 40));
        bt_clear.setMinimumSize(new java.awt.Dimension(40, 40));
        bt_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clearActionPerformed(evt);
            }
        });

        bt_plus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_plus.setText("+");
        bt_plus.setMaximumSize(new java.awt.Dimension(40, 40));
        bt_plus.setMinimumSize(new java.awt.Dimension(40, 40));
        bt_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_plusActionPerformed(evt);
            }
        });

        bt_over.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_over.setText("÷");
        bt_over.setMaximumSize(new java.awt.Dimension(40, 40));
        bt_over.setMinimumSize(new java.awt.Dimension(40, 40));
        bt_over.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_overActionPerformed(evt);
            }
        });

        bt_times.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_times.setText("x");
        bt_times.setMaximumSize(new java.awt.Dimension(40, 40));
        bt_times.setMinimumSize(new java.awt.Dimension(40, 40));
        bt_times.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_timesActionPerformed(evt);
            }
        });

        bt_equal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_equal.setText("=");
        bt_equal.setMaximumSize(new java.awt.Dimension(40, 40));
        bt_equal.setMinimumSize(new java.awt.Dimension(40, 40));
        bt_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_equalActionPerformed(evt);
            }
        });

        bt_minus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_minus.setText("-");
        bt_minus.setMaximumSize(new java.awt.Dimension(40, 40));
        bt_minus.setMinimumSize(new java.awt.Dimension(40, 40));
        bt_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_minusActionPerformed(evt);
            }
        });

        bt_seven.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_seven.setText("7");
        bt_seven.setMaximumSize(new java.awt.Dimension(40, 40));
        bt_seven.setMinimumSize(new java.awt.Dimension(40, 40));
        bt_seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sevenActionPerformed(evt);
            }
        });

        bt_four.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_four.setText("4");
        bt_four.setMaximumSize(new java.awt.Dimension(40, 40));
        bt_four.setMinimumSize(new java.awt.Dimension(40, 40));
        bt_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fourActionPerformed(evt);
            }
        });

        bt_one.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_one.setText("1");
        bt_one.setMaximumSize(new java.awt.Dimension(40, 40));
        bt_one.setMinimumSize(new java.awt.Dimension(40, 40));
        bt_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_oneActionPerformed(evt);
            }
        });

        bt_plus_minus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_plus_minus.setText("±");
        bt_plus_minus.setMaximumSize(new java.awt.Dimension(40, 40));
        bt_plus_minus.setMinimumSize(new java.awt.Dimension(40, 40));
        bt_plus_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_plus_minusActionPerformed(evt);
            }
        });

        bt_eight.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_eight.setText("8");
        bt_eight.setMaximumSize(new java.awt.Dimension(40, 40));
        bt_eight.setMinimumSize(new java.awt.Dimension(40, 40));
        bt_eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eightActionPerformed(evt);
            }
        });

        bt_five.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_five.setText("5");
        bt_five.setMaximumSize(new java.awt.Dimension(40, 40));
        bt_five.setMinimumSize(new java.awt.Dimension(40, 40));
        bt_five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fiveActionPerformed(evt);
            }
        });

        bt_two.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_two.setText("2");
        bt_two.setMaximumSize(new java.awt.Dimension(40, 40));
        bt_two.setMinimumSize(new java.awt.Dimension(40, 40));
        bt_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_twoActionPerformed(evt);
            }
        });

        bt_zero.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_zero.setText("0");
        bt_zero.setMaximumSize(new java.awt.Dimension(40, 40));
        bt_zero.setMinimumSize(new java.awt.Dimension(40, 40));
        bt_zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_zeroActionPerformed(evt);
            }
        });

        bt_nine.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_nine.setText("9");
        bt_nine.setMaximumSize(new java.awt.Dimension(40, 40));
        bt_nine.setMinimumSize(new java.awt.Dimension(40, 40));
        bt_nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nineActionPerformed(evt);
            }
        });

        bt_three.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_three.setText("3");
        bt_three.setMaximumSize(new java.awt.Dimension(40, 40));
        bt_three.setMinimumSize(new java.awt.Dimension(40, 40));
        bt_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_threeActionPerformed(evt);
            }
        });

        bt_six.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_six.setText("6");
        bt_six.setMaximumSize(new java.awt.Dimension(40, 40));
        bt_six.setMinimumSize(new java.awt.Dimension(40, 40));
        bt_six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sixActionPerformed(evt);
            }
        });

        decimal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        decimal.setText(".");
        decimal.setMaximumSize(new java.awt.Dimension(40, 40));
        decimal.setMinimumSize(new java.awt.Dimension(40, 40));
        decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bt_seven, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_eight, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_nine, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_times, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(bt_four, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_five, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_six, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(bt_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_plus_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_over, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_equal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_backspece, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(display, javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addComponent(bt_one, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(bt_two, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(bt_three, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(bt_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_two, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_one, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_three, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_four, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_five, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_six, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_seven, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_eight, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_nine, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_times, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_over, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_zero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_plus_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_backspece, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_zeroActionPerformed
        //actoin for button 0
          mCon.setData(bt_zero.getText());
    }//GEN-LAST:event_bt_zeroActionPerformed

    private void bt_sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sevenActionPerformed
        //actoin for button 7
          mCon.setData(bt_seven.getText());
    }//GEN-LAST:event_bt_sevenActionPerformed

    private void bt_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_oneActionPerformed
        //actoin for button 1
          mCon.setData(bt_one.getText());
    }//GEN-LAST:event_bt_oneActionPerformed

    private void bt_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_twoActionPerformed
        // actoin for button 2
         mCon.setData(bt_two.getText());
    }//GEN-LAST:event_bt_twoActionPerformed

    private void bt_threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_threeActionPerformed
        //actoin for button 3
         mCon.setData(bt_three.getText());
    }//GEN-LAST:event_bt_threeActionPerformed

    private void bt_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fourActionPerformed
       //actoin for button 4:
         mCon.setData(bt_four.getText());
    }//GEN-LAST:event_bt_fourActionPerformed

    private void bt_fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fiveActionPerformed
        //actoin for button 5
         mCon.setData(bt_five.getText());
    }//GEN-LAST:event_bt_fiveActionPerformed

    private void bt_sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sixActionPerformed
        //actoin for button 6
          mCon.setData(bt_six.getText());
    }//GEN-LAST:event_bt_sixActionPerformed

    private void bt_eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eightActionPerformed
        //actoin for button 8
       mCon.setData(bt_eight.getText());
    }//GEN-LAST:event_bt_eightActionPerformed

    private void bt_nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nineActionPerformed
        //actoin for button 9
        mCon.setData(bt_nine.getText());
    }//GEN-LAST:event_bt_nineActionPerformed

    private void decimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalActionPerformed
        //action for dot button
         mCon.setDot( decimal.getText());
    }//GEN-LAST:event_decimalActionPerformed

    private void bt_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clearActionPerformed
        // action for clear
        mCon.notation(bt_clear.getText());
    }//GEN-LAST:event_bt_clearActionPerformed

    private void bt_equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_equalActionPerformed
        // action for equal
          mCon.notation(bt_equal.getText());
    }//GEN-LAST:event_bt_equalActionPerformed

    private void bt_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_plusActionPerformed
        // action for +
        mCon.notation(bt_plus.getText());
    }//GEN-LAST:event_bt_plusActionPerformed

    private void bt_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_minusActionPerformed
       // action for -
        mCon.notation(bt_minus.getText());
    }//GEN-LAST:event_bt_minusActionPerformed

    private void bt_timesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_timesActionPerformed
        // action for x
        mCon.notation(bt_times.getText());
    }//GEN-LAST:event_bt_timesActionPerformed

    private void bt_overActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_overActionPerformed
          // action for ÷
        mCon.notation(bt_over.getText());
    }//GEN-LAST:event_bt_overActionPerformed

    private void bt_plus_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_plus_minusActionPerformed
          // action for +/-號
        mCon.notation(bt_plus_minus.getText());
        
    }//GEN-LAST:event_bt_plus_minusActionPerformed

    private void bt_ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ceActionPerformed
         // action for CE
        mCon.notation(bt_ce.getText());
    }//GEN-LAST:event_bt_ceActionPerformed

    private void bt_backspeceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backspeceActionPerformed
        // action for 倒退鍵
        mCon.notation(bt_backspece.getText());
    }//GEN-LAST:event_bt_backspeceActionPerformed

   
    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) {
        
        /**
         * New Calculator Controller View 物件
         * Calculator throw Controller
         * Controller throw View
         * View throw Controller
         * View add Observer
         */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            Calculator model = new Calculator();
            Controller cc = new Controller(model); 
             View view = new View(cc);
             view.setTitle("Calculator");
             cc.addView(view);
             view.setVisible(true);
             model.addObserver(view);
            }
        });
      
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton bt_backspece;
    private javax.swing.JButton bt_ce;
    private javax.swing.JButton bt_clear;
    private javax.swing.JButton bt_eight;
    private javax.swing.JButton bt_equal;
    private javax.swing.JButton bt_five;
    private javax.swing.JButton bt_four;
    private javax.swing.JButton bt_minus;
    private javax.swing.JButton bt_nine;
    private javax.swing.JButton bt_one;
    private javax.swing.JButton bt_over;
    private javax.swing.JButton bt_plus;
    private javax.swing.JButton bt_plus_minus;
    private javax.swing.JButton bt_seven;
    private javax.swing.JButton bt_six;
    private javax.swing.JButton bt_three;
    private javax.swing.JButton bt_times;
    private javax.swing.JButton bt_two;
    private javax.swing.JButton bt_zero;
    private javax.swing.JButton decimal;
    private javax.swing.JTextField display;
    private javax.swing.JDialog jDialog1;
    // End of variables declaration//GEN-END:variables
 
   /**
    * update display data
    * @param o
    * @param arg 
    */   
   @Override
    public void update(Observable o, Object arg) {
       display.setText(arg.toString());
    }

    
 
}

  



   

   

